apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: docker-gateway-service-k8s
spec:
  selector:
    matchLabels:
      app: docker-gateway-service-k8s #same for service
  replicas: 1 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: docker-gateway-service-k8s #label must be same
    spec:
      containers:
        - name: docker-gateway-service-k8s
          image: docker-gateway-service-k8s:1.0 # Image that will be used to containers in the cluster(version needed--from docker image tag)
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8989 # The port that the container is running on in the cluster
