spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: doctor-service
          uri: lb://DOCTOR-SERVICE
          predicates:
            - Path=/doctor/**
        - id: admission-service
          uri: lb://ADMISSION-SERVICE
          predicates:
            - Path=/admission/**

#id - used for calling from internal API
#URI - same as spring-app-name (mandatory)
#path - indicates @RequestMapping

server:
  port: 8989

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.49.2:31693/eureka/
  instance:
    instance:
    preferIpAddress: true
    hostname: localhost
    ipAddr: 192.168.49.2
